### ISSUE TITLE
set_html not working

### ISSUE THREAD

**Issue by dongjian** [fltk-rs/fltk-webview#10]
![image](https://user-images.githubusercontent.com/2841022/140939035-44af33d7-9b87-4e6f-942a-e5f38c6490c3.png)

windows 10

fltk = "1.2.14" // also tried 1.1
fltk-webview = "0.2.9"

wv.navigate("http://google.com"); works fine , but set_html is no response

**Comment by MoAlyousef** [comment]
Remove the first line of your string: `data:text/html` since it's already set using set_html

**Comment by MoAlyousef** [comment]
Does the original code sample work with wv.navigate() instead of set_html()?

**Comment by dongjian** [comment]
> Does the original code sample work with wv.navigate() instead of set_html()?

I see that bind.rs uses wv.navigate(HTML); But my call to wv.navigate (HTML) crashes : (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)

**Comment by MoAlyousef** [comment]
I've pushed what I think is a fix to a bug introduced in the last version.
Can you try building against the git repo:

```
[dependencies]
fltk = "1.2.14"
fltk-webview = { git = "https://github.com/fltk-rs/fltk-webview" }
```

**Comment by dongjian** [comment]
Thank you very much !!! yes it's works fine!!!

**Comment by MoAlyousef** [comment]
Great. I’ll publish a new version with the fix this evening.
