### ISSUE TITLE
resize window , the webview gets bigger

### ISSUE THREAD

**Issue by dongjian** [fltk-rs/fltk-webview#14]
Hi! 

 when I try laouts other window works fine , but the webview gets bigger and resizeble. like below

![image](https://user-images.githubusercontent.com/2841022/160086275-8f2809db-9831-49d6-b5d6-34d93a8d56b2.png)
![image](https://user-images.githubusercontent.com/2841022/160086363-b6293389-9af0-4e9a-bfd2-06540c6b32c9.png)
resize webview window
![image](https://user-images.githubusercontent.com/2841022/160086416-a88666bb-243a-4502-b0e1-070f61689642.png)
here is my code
```
fn main() {
    let a = app::App::default().with_scheme(app::Scheme::Gtk);
    let mut win = window::Window::default().with_size(640, 480);

    let mut col = Flex::new(0, 0, 400, 300, None);
    col.set_color(Color::Blue);
    col.set_type(group::FlexType::Column);
    //main_panel(&mut col);

    let mut test_win = window::Window::default();
    test_win.set_color(Color::Red);
    test_win.end();

    let mut wv_win = window::Window::default();
    wv_win.make_resizable(true);
    wv_win.set_border(false);
    wv_win.end();
    //col.set_size(&test_win2, 100);
    col.end();
    win.resizable(&col);
    win.set_color(enums::Color::from_rgb(250, 250, 250));

    win.end();
    win.show();
    win.size_range(600, 400, 0, 0);
    let mut wv = fltk_webview::Webview::create(false, &mut wv_win);
    wv.navigate("https://google.com");
    a.run().unwrap();
}
```
any help ?

**Comment by MoAlyousef** [comment]
It's not clear what you want to achieve. Also what's your operating system?

**Comment by dongjian** [comment]
> It's not clear what you want to achieve. Also what's your operating system?
![image](https://user-images.githubusercontent.com/2841022/160165757-c3e90813-5896-4588-97bd-ffebaf02dcbb.png)
I have a player like this . when I resize the window , the web view become bigger like this

![image](https://user-images.githubusercontent.com/2841022/160165989-38fd8b51-153e-4451-a168-06998799b4ab.png)
I am using win10 . Mac did not test yet .

**Comment by MoAlyousef** [comment]
And you don't want it to be resized when the main window is resized?

**Comment by dongjian** [comment]
I don't want webview become big. Is there any way to make webview hight same as vlcview when resize the window. I try flex but it not working.

**Comment by MoAlyousef** [comment]
You can put the webview window inside a group and make the group non-resizable.
```rust
fn main() {
    let a = app::App::default().with_scheme(app::Scheme::Gtk);
    let mut win = window::Window::default().with_size(640, 480);

    let mut col = group::Flex::new(0, 0, 400, 300, None);
    col.set_color(Color::Blue);
    col.set_type(group::FlexType::Column);
    //main_panel(&mut col);

    let mut test_win = window::Window::default();
    test_win.set_color(Color::Red);
    test_win.end();
    let mut grp = group::Group::default();
    let mut wv_win = window::Window::default().with_size(400, 200);
    wv_win.end();
    grp.end();
    grp.make_resizable(false);
    col.end();
    win.resizable(&col);
    win.set_color(Color::from_rgb(250, 250, 250));

    win.end();
    win.show();
    win.size_range(600, 400, 0, 0);
    let mut wv = fltk_webview::Webview::create(false, &mut wv_win);
    wv.navigate("https://google.com");
    a.run().unwrap();
}
```

**Comment by dongjian** [comment]
Thanks! it worked!  but It would be nicer if webview behaved like the other window
