### ISSUE TITLE
crashed on win7 

### ISSUE THREAD

**Issue by dongjian** [fltk-rs/fltk-webview#19]
I tried two versions of fltk-webview on Windows 7

[dependencies]
fltk-webview = "0.2"
crashed at
src/lib.rs:189:9
assert!(!inner.is_null());

[dependencies]
fltk-webview = { git = "https://github.com/fltk-rs/fltk-webview.git" }
The program cannot open because some dll are missing like
api-ms-win-ntuser-sysparams-l1-1-0.dll

**Comment by MoAlyousef** [comment]
Since fltk-webview currently uses the latest webview, from the webview documentation:
```md
Developers and end-users must have the [WebView2 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) installed on their system for any version of Windows before Windows 11.
```

**Comment by dongjian** [comment]
> Since fltk-webview currently uses the latest webview, from the webview documentation:
> 
> ```lisp
> Developers and end-users must have the [WebView2 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) installed on their system for any version of Windows before Windows 11.
> ```

https://github.com/webview/webview/pull/753   I did some research and found that webview seems to have some support for older versions of windows. But I don't know how to run his demo so I can't test it. Then I looked at webview2 is not support win7 .
Is there a fltk-webview version that supports win7? Thank you very much

**Comment by MoAlyousef** [comment]
You could try pinning to an older version, for example
fltk-webview = "=2.13"

Unfortunately I don’t have win7 to test on. But I think it was at version 2.14 that the underlying webview shifted from mshtml to edge on windows.

**Comment by SteffenL** [comment]
MS WebView2 version 109 was the last version to support Windows 7.

**Comment by dongjian** [comment]
Forgot to close issue. Downloading an older version of webview2 and recompiling it will fix the problem
